### ISSUE TITLE
Running time 

### ISSUE THREAD

**Issue by CWYuan08** [drostlab/orthologr#18]
Hi there,
I am running divergence_stratigraphy in r, I am wondering how long does it normally take? It has been a few hours and still hasn't finished..

Thank you 
Best 
CW

**Comment by HajkD** [comment]
Hi there,

it depends on how big the genomes are that you are using, the number cores you run orthologr on, and the speed of the cores you are using.

Do you have an example or more details about your run? Otherwise, it's impossible for me to answer the question.

In principle, with big genomes it can easily take several ours on a single core.

Cheers,
Hajk

**Comment by CWYuan08** [comment]
Thank you, it managed to finish!

Best
CW
