### ISSUE TITLE
File blastresult_AllColdShockProteins.fasta.csv could not be read correctly.

### ISSUE THREAD

**Issue by yasamanrezvani** [drostlab/orthologr#26]
Hi, Thanks for the nice package. 

I usually use the blast function giving two Genome file of 2 organism in fasta format and run the command. Here is the command: 

>blast(query_file = "/path/to/Bdivergens1802A_Genome.fasta", 
                      subject_file = "/path/to/BmicrotiATCC30222_Genome.fasta",
                      delete_corrupt_cds = T, seq_type = "protein",
                      format = "fasta", blast_algorithm = "blastp") 

So far I was able to get the output without any issue. 
What I am trying to do now is find the orthologs of couple of protein sequences in a single species. I have the proteins sequences in fasta format as well as the subject file. here is my command:

> orthlg <- orthologs(
  query_file = "/path/to/AllColdShockProteins.fasta",
  subject_files = "/path/to/BmicrotiATCC30222_Genome.fasta",
  seq_type = "protein", format = "fasta", eval = 0.0001)

I am not sure if i am doing something wrong!! I am getting the following error: 

> Error in value[[3L]](cond) : 
  File blastresult_AllColdShockProteins.fasta.csv could not be read correctly. Please check the correct path to blastresult_AllColdShockProteins.fasta.csv or whether BLAST did write the resulting hit table correctly.

Any Idea on how to fix it is so appreciated. 
Thanks

>

**Comment by HajkD** [comment]
Hi @yasamanrezvani 

Many thanks for contacting me. Would it be possible to give me a bit more information so that I can try to help resolving the issue?

Could you first try to restart the R session and rerun this function. Maybe some file was still present in the `tempdir()` that was overwritten or wrongly parsed.

If it still doesn't work, would it be possible to show me some example sequences and header files from the `AllColdShockProteins.fasta` and `BmicrotiATCC30222_Genome.fasta` files?

Does the function `orthologr::blast_rec()` work with the files you use for `orthologr::orthologs()`

I hope we can resolve this fairly swiftly!

Many thanks,
Hajk

**Comment by HajkD** [comment]
Hi @yasamanrezvani,

Does this still remain an issue or can I close this discussion?

Many thanks,
Hajk

**Comment by yasamanrezvani** [comment]
Hello,

Thanks for your follow up. I have been using your package and it's
working fine now.

Thanks,
Yasaman
